export const SET_ORDERS = "SET_ORDERS";
export const ADD_ORDER = "ADD_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const CHANGE_STATUS = "CHANGE_STATUS";
export const EDIT_ORDER = "EDIT_ORDER";

export const CHANGE_ORDER_STATUS_REQUESTED = "CHANGE_ORDER_STATUS_REQUESTED";
export const CHANGE_ORDER_STATUS_COMPLETED = "CHANGE_ORDER_STATUS_COMPLETED";
