export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
export const SAGA_SIGNUP = "SAGA_SIGNUP";
export const SAGA_SIGN_IN = "SAGA_SIGN_IN";
export const SIGN_IN = "SIGN_IN";
export const EDIT_USER = "EDIT_USER";

export const ADD_ORDER_CUSTOMER = "ADD_ORDER_CUSTOMER"
export const CHANGE_ORDER_STATUS_IN_WORK = 'CHANGE_ORDER_STATUS_IN_WORK'
export const CHANGE_ORDER_CUSTOMER_STATUS_REQUESTED = 'CHANGE_ORDER_CUSTOMER_STATUS_REQUESTED'
